### ISSUE TITLE
OptionsPage.java Issue

### ISSUE THREAD

**Issue by dsabzanov** [dsabzanov/SyncUI#1]
In the OptionsPage.java there are 2 buttons (lines 24 and 27) that can take you to 2 separate pages. How do I use the nextPage() function for both of these lines if nextPage() is meant to go to 1 page. 

I feel like this solution is simple but I'm not 100% sure. 
Any advice?

**Comment by gregsandoval** [comment]
Good point. Just use the old method of e-> setScene etc for that particular btn. Modify the code as needed.
